### ISSUE TITLE
Parser does not correctly parse rational number forms

### ISSUE THREAD

**Issue by CinchBlue** [uhmanoa-transpiler-project/shaka-scheme#12]
If you give `1/2` to the `parse` function, it does not correctly push the correct list form onto the list -- it pushes only `1`, or the numerator part.

We need to expand the parser for numbers so that it correctly peeks ahead and does the full parse for the number form.

**Comment by paulolemus** [comment]
I found the issue, the parser never checked the string in the number token for a period or a /. It is now fixed and exists on branch "issue12". I found another bug however, I am unable to declare or initialize a std::string without the compiler throwing many errors.

**Comment by paulolemus** [comment]
Fixed switch case scoping issue, fixed quote for both parsing functions, fixed number for both parsing functions.
