### ISSUE TITLE
Rewrite of core evaluation system to use compiler-based VM (Dybvig)

### ISSUE THREAD

**Issue by CinchBlue** [uhmanoa-transpiler-project/shaka-scheme#22]

**Comment by CinchBlue** [comment]
We are currently making our way towards this within the current semester at UH Manoa (Fall 2017). We are basing our VM on the heap-based implementation as described in "Three Implementation Models for Scheme" by R. Kent Dybvig.

**Comment by CinchBlue** [comment]
#29 is implementing this change based on "Three Implementation Models for Scheme" [1]. The heap-based virtual machine is our chosen model, implemented in the class `HeapVirtualMachine`.


[1] Dybvig, R. Kent. Three implementation models for scheme. Diss. University of North Carolina at Chapel Hill, 1987. [Link to PDF](http://www.cs.unm.edu/~williams/cs491/three-imp.pdf)

**Comment by btwooton** [comment]
As we finished implementing the `HeapVirtualMachine` last semester, and have already been utilizing it as the core evaluation mechanism for the interpreter, I am marking this issue as closed.
