### ISSUE TITLE
Make test cases for If, Define Quote, ProcCall, Expression

### ISSUE THREAD

**Issue by kyho22** [uhmanoa-transpiler-project/shaka-scheme#8]
If
Define
Quote
Proc Call

Expression

**Comment by CinchBlue** [comment]
I've made test cases for `if` and `define`. I don't remember if I did `lambda` and `quote` and `proccall` so far, so please do those.

**Comment by CinchBlue** [comment]
The evaluation model that we are adopting and transitioning over to invalidates this issue, as the code this would apply to would be on the version 0.1 branch. Closing.
